--------------------------------------------------------------------------------
--  Handler.......... : onAddSensor
--  Author........... : 
--  Description...... : 
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
function MovingObject.onAddSensor (  )
--------------------------------------------------------------------------------
-- 	log.message ( "MovingObject.onAddSensor" )
--     
--     local nChildren = object.getChildCount ( hObject )
--     
--     
--     if ( object.isKindOf ( hObject, object.kTypeShape ) ) then
--         sensor.add ( hObject )
--     end
-- 	
--     if nChildren > 0 then
--     
--         for i = 0, nChildren - 1
--         do
--         local hChild = object.getChildAt ( hObject, i )
--             if ( object.isKindOf ( hChild, object.kTypeShape ) ) then
--                 sensor.add ( hChild )
--             end
--         local nChildren = object.getChildCount( hChild )
--         log.message( "Has children: ", nChildren )
--             for i = 0, nChildren - 1
--             do
--             local hChild = object.getChildAt ( hChild, i )
--                 if ( object.isKindOf ( hChild, object.kTypeShape ) ) then
--                     this.addSensors ( hChild )
--                 end
--             local nChildren = object.getChildCount( hChild )
--             log.message( "Has children: ", nChildren )
--                 for i = 0, nChildren - 1
--                 do
--                 local hChild = object.getChildAt ( hChild, i )
--                     if ( object.isKindOf ( hChild, object.kTypeShape ) ) then
--                         this.addSensors ( hChild )
--                     end
--                 local nChildren = object.getChildCount( hChild )
--                 log.message( "Has children: ", nChildren )
-- 
--                     for i = 0, nChildren - 1
--                     do
--                     local hChild = object.getChildAt ( hChild, i )
--                         if ( object.isKindOf ( hChild, object.kTypeShape ) ) then
--                            this.addSensors ( hChild )
--                         end
--                     local nChildren = object.getChildCount( hChild )
--                     log.message( "Has children: ", nChildren )
-- 
--                         for i = 0, nChildren - 1
--                         do
--                         local hChild = object.getChildAt ( hChild, i )
--                             if ( object.isKindOf ( hChild, object.kTypeShape ) ) then
--                                 this.addSensors ( hChild )
--                             end
--                         local nChildren = object.getChildCount( hChild )
--                         log.message( "Has children: ", nChildren )
-- 
--                     
--                         --this.getChildObject ( hChild )
--                         end
--                     --this.getChildObject ( hChild )
--                     end
--                 --this.getChildObject ( hChild )
--                 end
--             --this.getChildObject ( hChild )
--             end
--         
--         
--         --this.getChildObject ( hChild )
--         end
--     end
-- 
	
--------------------------------------------------------------------------------
end
--------------------------------------------------------------------------------
